### ISSUE TITLE
Build failed on Xcode 7.3

### ISSUE THREAD

**Issue by zekunyan** [FuzzyAutocomplete/FuzzyAutocompletePlugin#121] opened 2016-03-23 17:30 UTC
I try to build FuzzyAutocompletePlugin on the latest Xcode 7.3 (7D175). But it failed.

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DVTTextCompletionInlinePreviewController", referenced from:
      l_OBJC_$_CATEGORY_DVTTextCompletionInlinePreviewController_$_FuzzyAutocomplete in DVTTextCompletionInlinePreviewController+FuzzyAutocomplete.o
      objc-class-ref in FuzzyAutocomplete.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by liuzhecodekiller** [comment] 2016-03-25 05:53
do you have solved this problem？ i have the same problem

**Comment by zekunyan** [comment] 2016-03-25 06:36
@liuzhecodekiller https://github.com/erikolofsson/FuzzyAutocompletePlugin @erikolofsson fixed it by ignoring some unavailable functions in Xcode 7.3. You can try it.

**Comment by liuzhecodekiller** [comment] 2016-03-25 06:38
Thanks ，i have solve it by same way with you！








------------------ 原始邮件 ------------------
发件人: "zekunyan";<notifications@github.com>;
发送时间: 2016年3月25日(星期五) 下午2:36
收件人: "FuzzyAutocomplete/FuzzyAutocompletePlugin"<FuzzyAutocompletePlugin@noreply.github.com>; 
抄送: "无名"<471340380@qq.com>; 
主题: Re: [FuzzyAutocompletePlugin] Build failed on Xcode 7.3 (#121)




@liuzhecodekiller https://github.com/erikolofsson/FuzzyAutocompletePlugin @erikolofsson fixed it by ignoring some unavailable functions in Xcode 7.3. You can try it.

**Comment by slazyk** [comment] 2016-03-25 19:53
Duplicate of #118

**Closed by slazyk** 2016-03-25 19:53 UTC
